# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 25fba7286e0ea31ac188aeb0a85bf6efa46d9bcabac08f85ba7307ccf1854588a39599aba938fa4ea4fc5c20bc5cff6385c4c2c5a954d056f243abb8b79926da

test:
  secret_key_base: 505137b52b2a267249a536a7d00888ef92fcb0b9b2c3777de97582132547427e57d61931d8e9c7bec0f1badba1ea5389ffe57a44ceae7bd7fc93ccdec1658415

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
